### PR TITLE
Add Powershell Support for `bbl print-env`

### PR DESCRIPTION
**Pull request by patrickhuber**
See issue #342 

Pull request adds support for powershell when using `bbl print-env`

1. If using windows, the default shell will be powershell
2. If using non windows platform, but the PSModulePath environment variable is set, the default shell will be powershell
3. otherwise the default shell is bash
4. the user can override the default shell by specifying `bbl print-env --shell powershell` or `bbl print-env --shell bash`

### CODE REVIEW

**Comment by cwlbraa** [comment]
This is great, thanks! I really appreciate that you went ahead and reorg'd out the logic into that `renderers` package. 

Anyways, I have a couple of questions. Please be patient with me because I acknowledge that I am mostly ignorant about modern windows. 

1. Will this break users already using POSIX-compliant shells on windows? Do those people even exist? switching on runtime.GOOS when we really wish we could be switching on something like `$SHELL`, no? but I don't know if powershell has a SHELL environment variable that it sets, but is `PSModulePath` equivalent?
2. How does the above bit interact with the windows subsystem for linux?
3. Is PSModulePath something that is set in every running powershell? If so, what if we chose our shell on the basis of that env var being set?
4. What happens if I'm running linux or darwin and I've installed powershell, but I'm not currently using it? 

Additionally, some nits:
1. The Bash renderer your wrote is actually a Posix shell renderer AFAICT, and should probably be named as such. 
2. If we're going to keep the GOOS switch for shell detection, the Linux/Darwin tests are duplicated.

**Comment by patrickhuber** [comment]
1. The only other shell that I can think of is CYGWIN, I can add a check for the CYGWIN environment variable and use the posix shell by default if that variable is present similar to how I'm checking for the PSModulePath. https://cygwin.com/cygwin-ug-net/using-cygwinenv.html. If the env var is present on windows, I'll have it default to POSIX. 

2. I tested it on the linux subsystem for windows. The fact that the binary is compiled for linux sets the GOOS field to 'linux'. 

3. For the PSModulePath, I checked running windows command host (cmd.exe) and the env var wasn't there. I checked in BASH on the windows subsystem for linux and the shell wasn't there. I checked running powershell in the mcr.microsoft.com/powershell docker image and the variable was present. I had a customer verify that the variable was only present when powershell was running on MAC. 

4. The environment variable is only set if you set it explicitly with `export PSModulePath=/path/to/modules` or if you are running the powershell interactive shell. See 3 for the tests that I performed. 

Thanks for the feedback, I'll update the name from `bash` to `posix`. 

I want to make sure both darwin and linux work, I realize this duplicates the tests but I can't exclude a platform without losing verification that it works (even though they flex the same codepath). Did you want me to just consolidate the logic?

**Comment by patrickhuber** [comment]
Sounds good. Latest commit removes the platform from the selection criteria and uses PSModulePath in the default case. Also switched `--shell` to `--shell-type` and changed `bash` to `posix` based on feedback.

**Comment by patrickhuber** [comment]
@cwlbraa 

Would it make more sense to have the `--shell-type` flag to be `--format` ? I was thinking this would be closer to what it is actually doing. This would also leave open the ability to do something like `--format json` or `--format yaml`

**Comment by cwlbraa** [comment]
@patrickhuber, I have no real preference as to shell-type vs format. Do what you will.

I pulled this down and tried to take it for a drive with OSX powershell. I'm not sure how different that is from how it works on windows, but as it stands there's something wrong with how you print newlines and carriage returns, or at least I don't know how to invoke this in powershell. In POSIX-ish shells, we do `eval "$(bbl print-env)"` to set variables so that `bosh env` and friends will work afterwards.

With this PR and powershell, I can't get `Invoke-Expression "$(bbl print-env)"` working, as it seems to flatten out the `\r\n`s that are necessary at the ends of lines. How might I use print-env in powershell to target a bosh?

**Comment by patrickhuber** [comment]
Can you try single quotes instead? I did a quick test on my mac and this style of invoke-expression seems to work:

```
invoke-expression '$env:TEST="hello"                                                          
>> $env:TEST1="hi"'
```

This assumes unix style line endings are used. Powershell strings with double quotes don't seem to work at all. I'm on the road so need to check the behavior with the code when I get back.

**Comment by patrick-huber-pivotal** [comment]
After further testing, this works the same as eval in bash:

```
invoke-expression ((invoke-expression 'bbl print-env') -join "`r`n")
```

I'm still investigating if there is a more terse way to express the same concept

**Comment by cwlbraa** [comment]
merged here: https://github.com/cloudfoundry/bosh-bootloader/commit/28a1331aa9859e91b3522061ec433c0e0db42f4a

**Pull request closed without merging**
