### PR TITLE
Adds load balancer for credhub

### PR DESCRIPTION
**Pull request by arghya88**

### CODE REVIEW

**Comment by arghya88** [comment]
@genevieve Can you review this

**Comment by genevieve** [comment]
Hey @arghya88!

We initially implemented this before coming to the conclusion that it would be really insecure to expose this port/credhub to the internet.

@evanfarrar and @nmahoney-pivotal can add more color to this or inform you if this perspective has changed.

**Comment by arghya88** [comment]
@genevieve would it make sense if I change the NLB to internal?

**Comment by cwlbraa** [comment]
@arghya88 there's also considerable discussion as to whether bosh-deployed services should have access to the director's credhub. Our current best-practices advice is that bosh-deployed services should point at their own, separate credhubs, and internally NLB'ing the director credhub runs counter to that advice.

**Comment by arghya88** [comment]
@cwlbraa This is not exposing the director credhub. Its exposing a separate runtime credhub VM through the NLB.

**Comment by cwlbraa** [comment]
I totally jumped to conclusions before even opening the README.md. I'm not entirely sure I understand why operators shouldn't do this if their cf service credhub has auth and scopes configured...

**Comment by cwlbraa** [comment]
04fb91f1d1d1dee4549d5967631fba635cc14528

**Pull request closed without merging**
