### PR TITLE
Add a plan-patch to add support for an OpenVPN server

### PR DESCRIPTION
**Pull request by paulcwarren**
Hi,

This PR adds support for a BOSH deployed OpenVPN server on AWS. It adds a new public subnet with a security group to allow VPN traffic on TCP port 1194. It also adds a `vip` network to the cloud-config so that the openvpn server can have a public IP assigned. To keep things simple, we are only utilizing the first availability zone. We are open to supporting multiple AZs, but couldn't find a way to craft an ops-file to update the cloud-config based on the terraform outputs non-programatically.  See [this post](https://cloudfoundry.slack.com/archives/C0FA9UNAH/p1552513669015400).

[#164386432](https://www.pivotaltracker.com/story/show/164386432)

_Paul
cc @davewalter @julian-hj

### CODE REVIEW

**Comment by paulcwarren** [comment]
Hello, curious about any updates on this PR? Is there any information you would like from us that could help y'all with merging this PR? 

We currently have a story blocked on this PR https://www.pivotaltracker.com/story/show/164386432. Any feedback would be appreciated.

**Comment by DennisDenuto** [comment]
Hello from Diego Persistence! Is there any update on this PR? 

The design of one of our pipelines depend on this PR, and knowing whether it will be merged upstream or whether we should solve this some other way would be really useful for the story we are working on (referenced above).

**Comment by Polar-Beard** [comment]
Thanks for this PR and for your patience 🙏 

Looks good to us, and we'll try to be more responsive in the future

**Comment by DennisDenuto** [comment]
Thanks! we appreciate you having a look at it!

**Pull request merged**
