### PR TITLE
Improve azure support

### PR DESCRIPTION
**Pull request by titilambert**
Hello I just added the following parameters for bbl plan --iaas=azure
```
  --azure-resource-group-name        Azure Resource Group Name        env: $BBL_AZURE_RESOURCE_GROUP_NAME
  --azure-vnet-resource-group-name   Azure Vnet Resource Group Name   env: $BBL_AZURE_VNET_RESOURCE_GROUP_NAME
  --azure-vnet-name                  Azure Vnet Name                  env: $BBL_AZURE_VNET_NAME
  --azure-subnet-name                Azure Subnet Name                env: $BBL_AZURE_SUBNET_NAME
  --azure-disable-publicip           Azure Do not use public IP       env: $BBL_AZURE_DISABLE_PUBLICIP
  --azure-cidr                       Azure CIDR                       env: $BBL_AZURE_CIDR
```

I did that because, in my case, the resource group, the VNet, the Subnet are already created and I don't want a public IP for the jumpbox.

### CODE REVIEW

**Comment by cwlbraa** [comment]
Hi Thibault! 

Sorry this took so long to get to. We took a look at it briefly a couple weeks ago, but I ended up going on vacation before we had time to formulate a proper response, and there was a lot of discussion around exactly how to handle this. Long story short, we can't accept this PR. However, we really do want to support your use case. 

These features don't well into the scope of our Go CLI. In particular, we don't want to be supporting many types of possible existing resources across 5 IAASes through terraform code generation. The integration test and feature-interop-matrix burden of such a feature set is far too large for our 1 pizza team to handle. However, a lot of work has already gone into adjusting the way bbl works to support these sort of advanced, user-provided configurations via collections of user-provided files that we call [plan patches](http://cloudfoundry.github.io/bosh-bootloader/advanced-configuration#plan-patches).

We've gone ahead and written a [plan patch](https://github.com/cloudfoundry/bosh-bootloader/tree/master/plan-patches/byoresource-group-azure) for using existing resource groups on azure as an example of how we'd use bbl's terraform extension points to accomplish the same task. Using that as a template, we hope you'll be able to successfully modify your environment to your liking. We'd love it if you'd like to PR some azure plan-patches to support the other features you implemented in this PR. 

Best,
Connor

**Comment by titilambert** [comment]
@cwlbraa Hello, Thanks for your answer.
I will try to port this PR to plan patch.
Quick question on the bbl source code: Is there any reason why there is no comments ?

**Comment by cwlbraa** [comment]
you mean like code comments? generally we try to comment on the code's behavior in our BDD-styled unit tests, which generally go pretty far into describing what each individual object does. their Ginkgo Describe, Context, and It blocks. 

A couple pieces of advice for writing terraform patches:
1. setting `count = var.some_boolean_flag ? 1 : 0` on a resource is about as close to a conditional as you can get in terraform.
2. Don't try to mess with the raw terraform/azure.tf templates, make your changes in a separate "aftermarket" plan patch.
3. If you're trying to write highly generalized, interoperable patches with a lot of on-off switches, I'd recommend first writing patches for your specific use case --- IE don't worry about the being able to support all combinations of preexisting resources -- just worry about the specific ones that you have that are preexisting.

**Comment by fpeyre** [comment]
@cwlbraa 
Hello, thanks for your feedback.

I have one question on  this subject.
Let say we want apply your [plan](https://github.com/cloudfoundry/bosh-bootloader/tree/master/plan-patches/byoresource-group-azure) patch for using an existing resource group on azure.

From what I understand, the first step is to make `bbl plan` and after add the files of the plan patch in my directory.

But currently, I can't use my own resource group  to make `bbl plan` (bbl take the value of  `--name` option and add  `-bosh` as resource group, and after check if this resource group exist, which is not the case )

Am I wrong ? Do we have an option to make a `bbl plan` without checking if the resource group exist on azure ?

**Pull request closed without merging**
